apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
  {{- with merge .Values.service.annotations .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: redis
      port: {{ .Values.service.ports.redis }}
      targetPort: redis
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector: {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
