{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
{{- $secretName := include "redis-cluster.fullname" . }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $password := "" }}
{{- if $existingSecret }}
  {{- $password = index $existingSecret.data "redis-password" | b64dec }}
{{- else }}
  {{- $password = .Values.auth.password | default (randAlphaNum 16) }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  redis-password: {{ $password | b64enc | quote }}
{{- end }}
